{
 "title": "Minecraft - Server",
 "description": "Minecraft Server Monitoring - heathcliff26/minecraft-exporter",
 "tags": [
  "minecraft",
  "papermc"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"minecraft-metrics\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "forge_tps_dim{instance=~\"$instance\"}",
     "legendFormat": "{{ dimension_name }}"
    },
    {
     "expr": "forge_tps_overall{instance=~\"$instance\"}",
     "legendFormat": "Overall"
    }
   ]
  },
  {
   "title": "Paper TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(paper_tps_1m{instance=~\"$instance\"})",
     "legendFormat": "1 Minute"
    },
    {
     "expr": "sum(paper_tps_5m{instance=~\"$instance\"})",
     "legendFormat": "5 Minute"
    },
    {
     "expr": "sum(paper_tps_15m{instance=~\"$instance\"})",
     "legendFormat": "15 Minute"
    }
   ]
  },
  {
   "title": "Play Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "minecraft_stat_playtime{instance=~\"$instance\"} / 20",
     "legendFormat": "{{ player }}"
    }
   ]
  },
  {
   "title": "Dynmap Tile Render Statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(dynmap_tile_render_stat{instance=~\"$instance\"}) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_stat_score{instance=~\"$instance\"}",
     "legendFormat": "{{ player }}"
    }
   ]
  },
  {
   "title": "Dynmap Chunk Loading Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "dynmap_chunk_loading_duration{instance=~\"$instance\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  }
 ]
}