{
 "title": "Minecraft - Player",
 "description": "Minecraft Player Monitoring - heathcliff26/minecraft-exporter",
 "tags": [
  "minecraft",
  "papermc"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values({job=\"minecraft-metrics\"},instance)"
    }
   },
   {
    "name": "player",
    "label": "Player",
    "query": {
     "query": "label_values(minecraft_stat_blocks_mined{instance=~\"$instance\"},player)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Players Online",
   "type": "table",
   "gridPos": { "h": 18, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max(minecraft_player_online{instance=~\"$instance\"}) by (player, instance)",
     "legendFormat": "{{player}}"
    }
   ]
  },
  {
   "title": "Blocks Mined",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_stat_blocks_mined{instance=~\"$instance\",player=\"$player\"}) by (instance)",
     "legendFormat": "{{block}}"
    }
   ]
  },
  {
   "title": "Items Crafted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_stat_blocks_crafted{instance=~\"$instance\",player=\"$player\"}) by (instance)",
     "legendFormat": "{{block}}"
    }
   ]
  },
  {
   "title": "Blocks Collected",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(minecraft_stat_blocks_picked_up{instance=~\"$instance\",player=\"$player\"}) by (instance)",
     "legendFormat": "{{block}}"
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(minecraft_stat_deaths{instance=~\"$instance\",player=\"$player\",cause=\"minecraft:deaths\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Jumps",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "minecraft_stat_jumps{instance=~\"$instance\",player=\"$player\"}"
    }
   ]
  },
  {
   "title": "Meters Travelled",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "expr": "minecraft_stat_cm_traveled{instance=~\"$instance\",player=\"$player\"} / 100",
     "legendFormat": "{{  method }}"
    }
   ]
  },
  {
   "title": "Mobs Killed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "minecraft_stat_entities_killed{instance=~\"$instance\",player=\"$player\"}",
     "legendFormat": "{{ entity }}"
    }
   ]
  }
 ]
}