apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: prometheus-root-redirect
  namespace: monitoring
spec:
  redirectRegex:
    regex: ^/prometheus/?$
    replacement: /prometheus/query
