apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: discord-receiver
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: monitoring
spec:
  route:
    receiver: discord-critical
    repeatInterval: 4h
    matchers:
      - name: severity
        value: critical|warning
        regex: true
  receivers:
    - name: discord-critical
      discordConfigs:
        - apiURL:
            key: webhook-url
            name: alertmanager-discord-webhook
          sendResolved: true
      webhookConfigs:
        - url: http://incident-responder.discord-bot:8080/webhook
          sendResolved: true
