apiVersion: v1
kind: ServiceAccount
metadata:
  name: health-checker
  namespace: monitoring
  labels:
    app: health-checker
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: health-checker
  namespace: monitoring
  labels:
    app: health-checker
spec:
  schedule: "0 */3 * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  successfulJobsHistoryLimit: 1
  startingDeadlineSeconds: 600
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: health-checker
        spec:
          serviceAccountName: health-checker
          restartPolicy: OnFailure
          containers:
            - name: checker
              image: evince55/health-checker:latest
              imagePullPolicy: Always
              env:
                - name: DISCORD_WEBHOOK_URL
                  valueFrom:
                    secretKeyRef:
                      name: health-checker
                      key: webhook-url
              resources:
                limits:
                  memory: 128Mi
                  cpu: "250m"
                requests:
                  memory: 32Mi
                  cpu: 25m
