apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: discord-bot
  namespace: discord-bot
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store
  target:
    name: discord-bot
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: discord-token
      remoteRef:
        key: discord-bot-token
    - secretKey: rcon-password
      remoteRef:
        key: minecraft-rcon-password
