apiVersion: v1
kind: Service
metadata:
  name: incident-responder
  namespace: discord-bot
  labels:
    app: incident-responder
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: incident-responder
  type: ClusterIP
