apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: incident-responder
  namespace: discord-bot
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-kv-store
  target:
    name: incident-responder
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: webhook-url
      remoteRef:
        key: discord-webhook
