apiVersion: v1
kind: Service
metadata:
  name: minecraft-rcon
  namespace: default
  labels:
    app: minecraft
spec:
  ports:
    - name: rcon
      port: 25575
      targetPort: 25575
      protocol: TCP
  selector:
    app: minecraft
  type: ClusterIP
